server:
  port: 8081

spring:
  application:
    name: usuarios-service
  datasource:
    url: jdbc:h2:mem:usuariosdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

app:
  jwt:
    secret: ${JWT_SECRET:clave-super-secreta-de-prueba-para-firmar-jwt-2026}
    expiration-ms: 3600000
